# Generated by Django 6.0.3 on 2026-03-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablesRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('dateReservation', models.DateField()),
                ('nbPersonnes', models.IntegerField()),
                ('statut', models.CharField(max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tablesRestaurant.tablesrestaurant')),
            ],
        ),
    ]
