# Generated by Django 6.0.3 on 2026-03-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('menu', '0001_initial'),
        ('tablesRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCommande', models.DateField(auto_now=True)),
                ('statut', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=10, default=0.0, max_digits=10)),
                ('Utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to='account.utilisateur')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commmandes', to='tablesRestaurant.tablesrestaurant')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sousTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='orders.commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.plat')),
            ],
        ),
    ]
