# Generated by Django 6.0.3 on 2026-03-29 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFacture', models.DateTimeField(auto_now_add=True)),
                ('montantTotal', models.FloatField()),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='orders.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modePaiement', models.CharField(max_length=50)),
                ('datePaiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.FloatField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='payments.facture')),
            ],
        ),
    ]
